trigger:
- main

pool:
  vmImage: ubuntu-latest

pr:
  branches:
    include:
    - '*'  

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -la
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install package'
    publishJUnitResults: false
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    targetPath: '$(Pipeline.Workspace)'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo  $(env) && cd $(build.artifactstagingdirectory) & ls